name: reservation_client
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

scripts:
  build: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch --delete-conflicting-outputs
  change_icons: dart run flutter_launcher_icons
  flutter_native_splash: dart run flutter_native_splash:create

dependencies:
  flutter:
    sdk: flutter
  dio:
  intl: 
  json_annotation: 
  auto_route: 
  cached_network_image: 
  flutter_bloc: 
  equatable: 
  get_it: 
  form_builder_validators:
  flutter_advanced_drawer: ^1.3.7 
  screentasia:
  google_fonts: 
  # shared_preferences: 
  encrypt_shared_preferences: 
  pinput: 
  device_info_plus: 
  qr_flutter: 
  local_auth: 
  shimmer: 
  animated_bottom_navigation_bar: 
  infinite_scroll_pagination: 
  uuid: 
  loader_overlay: 
  syncfusion_flutter_datagrid: 
  expandable: 
  flutter_keyboard_visibility: 
  flutter_native_splash: 
  introduction_screen: 
  fk_user_agent: 
  flutter_svg:
  another_flushbar: 
  searchable_paginated_dropdown: 
  flutter_cache_manager: 
  go_router: 
  url_launcher: 
  floating_action_bubble:
  path_provider: 
  open_file: 
  permission_handler: 
  flutter_local_notifications: 
  new_version_plus: 
  universal_html: 
  carousel_slider: 
  lottie:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any

  analyzer: ^6.4.0
  auto_route_generator: ^8.0.0
  # dependency_validator: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  change_app_package_name: ^1.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
